[package]
name = "nhentai_dl"
version = "0.2.0"
edition = "2021"
authors = ["FWFWLL ffl@vivaldi.net"]

[dependencies]
image = "0.24.3"
rayon = "1.5.3"
reqwest = {version = "0.11.11", features = ["blocking"]}
scraper = "0.13.0"
tokio = {version = "1.20.1", features = ["full"]}
